import '@/build/core/styles/index.scss'
import '@fortawesome/fontawesome-free/js/all'
import '@/app/utilities/simplebar-components'
import '@/app/utilities/bootstrap-components'
import '@/app/utilities/core-components'